/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyzeNameVersionRouteImport } from './routes/analyze.$name.$version'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeNameVersionRoute = AnalyzeNameVersionRouteImport.update({
  id: '/analyze/$name/$version',
  path: '/analyze/$name/$version',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyze/$name/$version': typeof AnalyzeNameVersionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyze/$name/$version': typeof AnalyzeNameVersionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyze/$name/$version': typeof AnalyzeNameVersionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/analyze/$name/$version'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analyze/$name/$version'
  id: '__root__' | '/' | '/analyze/$name/$version'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzeNameVersionRoute: typeof AnalyzeNameVersionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze/$name/$version': {
      id: '/analyze/$name/$version'
      path: '/analyze/$name/$version'
      fullPath: '/analyze/$name/$version'
      preLoaderRoute: typeof AnalyzeNameVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzeNameVersionRoute: AnalyzeNameVersionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
