/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BadgesRouteImport } from './routes/badges'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PackageSplatRouteImport } from './routes/package/$'
import { Route as BatchIdRouteImport } from './routes/batch/$id'

const BadgesRoute = BadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PackageSplatRoute = PackageSplatRouteImport.update({
  id: '/package/$',
  path: '/package/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchIdRoute = BatchIdRouteImport.update({
  id: '/batch/$id',
  path: '/batch/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/badges': typeof BadgesRoute
  '/batch/$id': typeof BatchIdRoute
  '/package/$': typeof PackageSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/badges': typeof BadgesRoute
  '/batch/$id': typeof BatchIdRoute
  '/package/$': typeof PackageSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/badges': typeof BadgesRoute
  '/batch/$id': typeof BatchIdRoute
  '/package/$': typeof PackageSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/badges' | '/batch/$id' | '/package/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/badges' | '/batch/$id' | '/package/$'
  id: '__root__' | '/' | '/badges' | '/batch/$id' | '/package/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BadgesRoute: typeof BadgesRoute
  BatchIdRoute: typeof BatchIdRoute
  PackageSplatRoute: typeof PackageSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/badges': {
      id: '/badges'
      path: '/badges'
      fullPath: '/badges'
      preLoaderRoute: typeof BadgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/package/$': {
      id: '/package/$'
      path: '/package/$'
      fullPath: '/package/$'
      preLoaderRoute: typeof PackageSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batch/$id': {
      id: '/batch/$id'
      path: '/batch/$id'
      fullPath: '/batch/$id'
      preLoaderRoute: typeof BatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BadgesRoute: BadgesRoute,
  BatchIdRoute: BatchIdRoute,
  PackageSplatRoute: PackageSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
